
alias apagar="sudo shutdown -h now"
alias ..="cd .."
alias cl=clear
alias ll="ls -lav --color=auto"
alias g="google-chrome &"
alias ls="ls -lhF --color=auto"
alias la="la -lahF --color=auto"
alias tareas="gtg &"
alias escanear="gscan2pdf &"
alias montar="sudo mountpy -m"
alias grabarcd="brasero &"
alias particiones="lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT"
alias config_impresora="system-config-printer &"
alias calculadora="gcalctool"
alias puertos="sudo netstat -lunpt | grep :"
alias virtuales-kvm="sudo virt-manager --no-fork"
alias ver_impresoras="sudo lpinfo -v"
alias pantallas="sudo arandr"
alias admin-impresoras="sudo admin-system-printer &"
alias conecta-wifi="sudo wicd-curses"
alias editor-latex="texstudio &"
alias cp="gcp"
alias vaciar_papelera="trash-empty"
alias cliente-iax="sflphone"
alias cliente-sip="linphone"
alias cambiaMAC="funcionCambiaMAC"
alias leer_RSS="newsbeuter -r"
alias cliente-vnc="remmina"
alias monitor-discos="baobab &"
